import { useState } from "react";
import { getBackendUrl } from "@/config/env";

const BACKEND_URL = getBackendUrl();

// Downloads the CV PDF (lang: "en" | "pt") generated by the backend.
export default function useCvDownload() {
  const [loading, setLoading] = useState(false);

  const download = async (lang = "en") => {
    try {
      setLoading(true);
      const res = await fetch(`${BACKEND_URL}/api/cv?lang=${lang}`);
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = lang === "pt" ? "Arthur_de_Oliveira_CV_PT.pdf" : "Arthur_de_Oliveira_Resume_EN.pdf";
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
    }
  };

  return { download, loading };
}
